services:
  mongodb:
    image: mongo:5.0
    container_name: shopping-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_shopping_data:/data/db
    networks:
      - shopping-network

  backend:
    build:
      context: ./back-end
    env_file:
      - ./back-end/.env
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - shopping-network

  frontend:
    build:
      context: ./front-end
    env_file:
      - ./front-end/.env
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    command: npm run dev -- --host
    networks:
      - shopping-network

volumes:
  mongo_shopping_data:


networks:
  shopping-network:
    driver: bridge
